server:
  port: 8080

#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?rewriteBatchedStatements=true
    username: root
    password: 666
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

#Mybatis配置
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: true
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  type-aliases-package: com.example.pojo
  global-config:
    banner: false
    db-config:
      id-type: auto
      logic-delete-field: deleted
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    #operations-sorter: order
    persist-authorization: true
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      display-name: '测试'
      paths-to-match: '/**'
      packages-to-scan: com.example
  default-flat-param-object: true
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
#阿里云
aliyun:
  oss:
    endpoint: https://oss-cn-chengdu.aliyuncs.com
    access-key-id: LTAI5tFb25mLmvMANonwq8Fo
    access-key-secret: HLXkaZQqkYClRonSlPsAofewkaSnSt
    bucket-name: ds-web-test
common:
  token-header: Authorization
